### ISSUE TITLE
Update better-sqlite3 dependency.

### ISSUE THREAD

**Issue by luizgununes** [eslachance/enmap#121]
If you are the latest version of node and enmap, you may find this error when running the project:

`Error: The module '/.../node_modules/enmap/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 120. This version of Node.js requires
NODE_MODULE_VERSION 115. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at bindings (/Users/lgnunes/Projetos/torenzala-bot/node_modules/bindings/bindings.js:112:48)
    at new Database (/Users/lgnunes/Projetos/torenzala-bot/node_modules/enmap/node_modules/better-sqlite3/lib/database.js:48:64)
    at new Enmap (/Users/lgnunes/Projetos/torenzala-bot/node_modules/enmap/src/index.js:156:18)
    at Object.<anonymous> (/Users/lgnunes/Projetos/torenzala-bot/index.js:11:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14) {
  code: 'ERR_DLOPEN_FAILED'`

**Comment by c0reme** [comment]
> Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`)

Since you have updated your node, you will need to update `package-lock.json` etc since it thinks you are using the previous node version. To fix, please do `npm rebuild` or `npm install`.


Please also note that better-sqlite3 only works on LTS versions of node, if have not installed a LTS version it will not work as expected.

**Comment by luizgununes** [comment]
> > Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`)
> 
> Since you have updated your node, you will need to update `package-lock.json` etc since it thinks you are using the previous node version. To fix, please do `npm rebuild` or `npm install`.
> 
> Please also note that better-sqlite3 only works on LTS versions of node, if have not installed a LTS version it will not work as expected.

My node is at 20.1.1 which is LTS. I already deleted the package-lock.json and node_module. Rebuild didn't work too.
I'm trying to use the enmap library that isn't updated since 9 months ago and has better-sqlite3 as dependency. I changed at the package-lock the version of the better-sqlite3 like at the package.json of enmap and still not work.

**Comment by luizgununes** [comment]
Yea, I know that. Even removing enmap and installing again, it seems to keep installing the 8.7.0 version of better-sqlite3. But no problem, I'm refactoring to use another kind of database. Downgrade node isn't an option too because I have another project running in the same machine.

**Comment by c0reme** [comment]
Version 8.7.0 of better-sqlite3 is the same as mine, in the same files. But thank you for trying though, sorry it didn't work for you.
