### ISSUE TITLE
Errors when attempting use of enmap

### ISSUE THREAD

**Issue by RileyDatLord** [eslachance/enmap#14]
I get these errors when using enmap:

```js
/root/Development/Bots/node_modules/enmap/src/index.js:84
  async fetch(keyOrKeys) {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/Development/Bots/node_modules/enmap/index.js:1:77)
```

**Comment by RileyDatLord** [comment]
Found Fix

**Comment by bambalamb** [comment]
@RileyDatLord Could you talk about your fix?

**Comment by eslachance** [comment]
@bambalamb the answer is to update node to version 8 or higher.

**Comment by w0298i** [comment]
You could use the Babel transpiler.
