### ISSUE TITLE
Error when starting enmap.

### ISSUE THREAD

**Issue by Random568** [eslachance/enmap#33]
node_modules/enmap/src/index.js:260
  static async migrate() {
               ^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/web/nodejs/BotBeta/node_modules/enmap/index.js:1:77)

**Comment by veksen** [comment]
What version of Node? I assume an older version is causing your issue.

**Comment by g-rosenberger** [comment]
Oh, yes thanks.
