### ISSUE TITLE
Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by devmadudu** [eslachance/enmap#50]
Hello! When I try to start my node app it says `Error: Could not locate the bindings file. Tried:` and I cant fix it! Please help!

Console:
```bash
$ node .
D:\Bots\enmaptest\node_modules\leveldown\node_modules\bindings\bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → D:\Bots\enmaptest\node_modules\leveldown\build\leveldown.node
 → D:\Bots\enmaptest\node_modules\leveldown\build\Debug\leveldown.node
 → D:\Bots\enmaptest\node_modules\leveldown\build\Release\leveldown.node
 → D:\Bots\enmaptest\node_modules\leveldown\out\Debug\leveldown.node
 → D:\Bots\enmaptest\node_modules\leveldown\Debug\leveldown.node
 → D:\Bots\enmaptest\node_modules\leveldown\out\Release\leveldown.node
 → D:\Bots\enmaptest\node_modules\leveldown\Release\leveldown.node
 → D:\Bots\enmaptest\node_modules\leveldown\build\default\leveldown.node
 → D:\Bots\enmaptest\node_modules\leveldown\compiled\14.10.1\win32\x64\leveldown.node
    at bindings (D:\Bots\enmaptest\node_modules\←[4mleveldown←[24m\node_modules\←[4mbindings←[24m\bindings.js:88:9)
    at Object.<anonymous> (D:\Bots\enmaptest\node_modules\←[4mleveldown←[24m\leveldown.js:4:46)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1076:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:941:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:782:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:965:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (D:\Bots\enmaptest\node_modules\←[4mlevel←[24m\level.js:1:44)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1076:30)←[39m {
  tries: [
    ←[32m'D:\\Bots\\enmaptest\\node_modules\\leveldown\\build\\leveldown.node'←[39m,
    ←[32m'D:\\Bots\\enmaptest\\node_modules\\leveldown\\build\\Debug\\leveldown.node'←[39m,
    ←[32m'D:\\Bots\\enmaptest\\node_modules\\leveldown\\build\\Release\\leveldown.node'←[39m,
    ←[32m'D:\\Bots\\enmaptest\\node_modules\\leveldown\\out\\Debug\\leveldown.node'←[39m,
    ←[32m'D:\\Bots\\enmaptest\\node_modules\\leveldown\\Debug\\leveldown.node'←[39m,
    ←[32m'D:\\Bots\\enmaptest\\node_modules\\leveldown\\out\\Release\\leveldown.node'←[39m,
    ←[32m'D:\\Bots\\enmaptest\\node_modules\\leveldown\\Release\\leveldown.node'←[39m,
    ←[32m'D:\\Bots\\enmaptest\\node_modules\\leveldown\\build\\default\\leveldown.node'←[39m,
    ←[32m'D:\\Bots\\enmaptest\\node_modules\\leveldown\\compiled\\14.10.1\\win32\\x64\\leveldown.node'←[39m
  ]
}
```

**Comment by eslachance** [comment]
*leveldown* is not used by enmap. please remove it from your dependencies, your build error isn't related to this module.
