### ISSUE TITLE
gyp ERR! stack Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by progamer68** [eslachance/enmap#64]
Hello! I'm using repl.it for my music bot, but I get this error while installing enmap.

```
make: Entering directory '/home/runner/Firefly/node_modules/better-sqlite3/build'
  TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
  TOUCH Release/obj.target/deps/locate_sqlite3.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
deps/sqlite3.target.mk:183: recipe for target 'Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o' failed
make: *** [Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o] Error 4
rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
make: Leaving directory '/home/runner/Firefly/node_modules/better-sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/runner/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-1019-gcp
gyp ERR! command "/home/runner/.nvm/versions/node/v13.8.0/bin/node" "/home/runner/.nvm/versions/node/v13.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/runner/Firefly/node_modules/better-sqlite3
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.4 build-release: `node-gyp rebuild --release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the better-sqlite3@7.1.4 build-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-03T11_01_39_471Z-debug.log
[            ......] - install: info lifecycle better-sqlite3@7.1.4~install:[            ......] \ install: info lifecycle better-sqlite3@7.1.4~install:[            ......] \ install: info lifecycle better-sqlite3@7.1.4~install:[            ......] \ install: info lifecycle better-sqlite3@7.1.4~install:[            ......] \ install: info lifecycle better-sqlite3@7.1.4~install:[            ......] \ install: info lifecycle better-sqlite3@7.1.4~install:[            ......] \ install: info lifecycle better-sqlite3@7.1.4~install:npm WARN FIREFLY2@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! better-sqlite3@7.1.4 install: `prebuild-install || npm run build-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the better-sqlite3@7.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-03T11_01_42_049Z-debug.log
```

**Comment by eslachance** [comment]
`Killed` means that the process ran out of memory while attempting to build the output. Unfortunately that's not something I can fix. You can join the repl.it Discord if you want more help on the matter.
https://discord.com/invite/5gcPC6B

**Comment by progamer68** [comment]
Thank you!
