### ISSUE TITLE
Enmap won't install on M1 MacBook Air

### ISSUE THREAD

**Issue by xgoje** [eslachance/enmap#86]
```bash
npm ERR! code 1
npm ERR! path /Users/redacted/discord-bots/Discord Bots/ArgonBots/ADMINBOTS/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c prebuild-install || npm run build-release
npm ERR! > better-sqlite3@7.4.4 build-release
npm ERR! > node-gyp rebuild --release
npm ERR! 
npm ERR!   TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR!   ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR! rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=16.13.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.2.0
npm ERR! gyp info using node@16.13.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.7 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/redacted/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/redacted/discord-bots/Discord Bots/ArgonBots/ADMINBOTS/node_modules/better-sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/redacted/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/redacted/Library/Caches/node-gyp/16.13.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/redacted/Library/Caches/node-gyp/16.13.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/redacted/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/redacted/Library/Caches/node-gyp/16.13.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/redacted/discord-bots/Discord Bots/ArgonBots/ADMINBOTS/node_modules/better-sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! /bin/sh: Bots/ArgonBots/ADMINBOTS/node_modules/better-sqlite3/build/Release/lib.host:/Users/redacted/discord-bots/Discord: No such file or directory
npm ERR! /Users/redacted/discord-bots/Discord Bots/ArgonBots/ADMINBOTS/node_modules/better-sqlite3/deps/extract.js:8
npm ERR! process.on('unhandledRejection', (err) => { throw err; });
npm ERR!                                             ^
npm ERR! 
npm ERR! CwdError: ENOENT: Cannot cd into '/Users/redacted/discord-bots/Discord Bots/ArgonBots/ADMINBOTS/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3'
npm ERR!     at /Users/redacted/discord-bots/Discord Bots/ArgonBots/ADMINBOTS/node_modules/tar/lib/mkdir.js:43:12
npm ERR!     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR!   path: '/Users/redacted/discord-bots/Discord Bots/ArgonBots/ADMINBOTS/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3',
npm ERR!   code: 'ENOENT'
npm ERR! }
npm ERR! make: *** [b857c92884e9598d609f6be182a2595df7a8e00f.intermediate] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/redacted/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 21.1.0
npm ERR! gyp ERR! command "/Users/redacted/.nvm/versions/node/v16.13.0/bin/node" "/Users/redacted/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/redacted/discord-bots/Discord Bots/ArgonBots/ADMINBOTS/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v16.13.0
npm ERR! gyp ERR! node-gyp -v v8.2.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/redacted/.npm/_logs/2021-11-08T22_39_09_326Z-debug.log
```

**Comment by WilsontheWolf** [comment]
Hello there. The build process here is actually part of better-sqlite3 and as such is an issue there. However, I did notice there is a space in your folder. Better-sqlite3 often errors if there is a space (or other no-Latin characters) in the path. Please remove that space and try again.

**Comment by xgoje** [comment]
Thanks!
