### ISSUE TITLE
Cen't delete the hole database

### ISSUE THREAD

**Issue by Paul52Games** [eslachance/enmap#9]
When i do `woorden.deleteAll()` it's giving this error: 
```C:\Users\Paul\node_modules\enmap\src\index.js:433
        this.db.bulkDelete();
                ^

TypeError: this.db.bulkDelete is not a function
    at Map.deleteAll (C:\Users\Paul\node_modules\enmap\src\index.js:433:17)
    at Client.bot.on.message (C:\Users\Paul\Desktop\discord bots\school\bot.js:142:13)
    at emitOne (events.js:115:13)
    at Client.emit (events.js:210:7)
    at MessageCreateHandler.handle (C:\Users\Paul\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\Paul\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Paul\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\Paul\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\Paul\node_modules\discord.js\node_modules\ws\lib\event-target.js:120:16)
    at emitOne (events.js:115:13)```

**Comment by Paul52Games** [comment]
i also reïnstalled enmap and enmap-level, but that dos not work

**Comment by eslachance** [comment]
That's actually my fault, I forgot to implement this in the providers. Will be doing that as soon as I get a chance. In the meantime, if you do `woorden.deleteAll(false)` it'll work by deleting every row individually, which is a bit slower but will work.
