### ISSUE TITLE
TypeError: data.findIndex is not a function

### ISSUE THREAD

**Issue by Sedorikku1949** [eslachance/enmap#98]
Hey, i have find a bug on Enmap !
The error is:
```js
TypeError: data.findIndex is not a function
    at Enmap.remove (Z:\code\kady\kadyBeta\node_modules\enmap\src\index.js:837:24)
    at eval (eval at <anonymous> (Z:\code\kady\kadyBeta\_interactions\cmd\dev\eval.js:25:23), <anonymous>:1:39)
    at Z:\code\kady\kadyBeta\_interactions\cmd\dev\eval.js:25:23
    at new Promise (<anonymous>)
    at Command.exec (Z:\code\kady\kadyBeta\_interactions\cmd\dev\eval.js:21:15)
    at CommandManager.execute (Z:\code\kady\kadyBeta\_core\_managers\CommandManager.js:84:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async commandHandler (Z:\code\kady\kadyBeta\_listeners\nop\messageCreate.js:54:2) {
  [stack]: 'TypeError: data.findIndex is not a function\n' +
    '    at Enmap.remove (Z:\\code\\kady\\kadyBeta\\node_modules\\enmap\\src\\index.js:837:24)\n' +
    '    at eval (eval at <anonymous> (Z:\\code\\kady\\kadyBeta\\_interactions\\cmd\\dev\\eval.js:25:23), <anonymous>:1:39)\n' +
    '    at Z:\\code\\kady\\kadyBeta\\_interactions\\cmd\\dev\\eval.js:25:23\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at Command.exec (Z:\\code\\kady\\kadyBeta\\_interactions\\cmd\\dev\\eval.js:21:15)\n' +
    '    at CommandManager.execute (Z:\\code\\kady\\kadyBeta\\_core\\_managers\\CommandManager.js:84:27)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at async commandHandler (Z:\\code\\kady\\kadyBeta\\_listeners\\nop\\messageCreate.js:54:2)',
  [message]: 'data.findIndex is not a function'
}
```
The error occurred when I tried to push a string into an object.

**Comment by eslachance** [comment]
This feels like you have an old version of enmap. data.findIndex is not located at line 837 of the current code. Perhaps make sure you're on the lastest version, 5.9.1...

**Comment by Sedorikku1949** [comment]
Woups, sorry 😶
